package com.yzgeneration.evc.mock.usedItem;

import com.yzgeneration.evc.image.model.UsedItemImage;
import com.yzgeneration.evc.image.service.port.UsedItemImageRepository;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

public class FakeUsedItemImageRepository implements UsedItemImageRepository {

    private static Long autoGeneratedId = 0L;
    private final List<UsedItemImage> mockUsedItemImages = new ArrayList<>();

    @Override
    public UsedItemImage save(UsedItemImage usedItemImage) {
        UsedItemImage mockUsedItemImage = UsedItemImage.builder()
                .id(++autoGeneratedId)
                .usedItemId(usedItemImage.getUsedItemId())
                .imageURL(usedItemImage.getImageURL())
                .build();

        mockUsedItemImages.add(mockUsedItemImage);

        return mockUsedItemImage;
    }

    @Override
    public List<String> findImageUrlsById(Long usedItemId) {
        return mockUsedItemImages.stream()
                .filter(mockUsedItemImage -> Objects.equals(mockUsedItemImage.getUsedItemId(), usedItemId))
                .map(UsedItemImage::getImageURL).toList();
    }
}
