package com.yzgeneration.evc.mock.usedItem;

import com.yzgeneration.evc.domain.image.enums.ItemType;
import com.yzgeneration.evc.domain.image.model.Image;
import com.yzgeneration.evc.domain.image.service.port.ImageRepository;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

public class FakeImageRepository implements ImageRepository {

    private static Long autoGeneratedId = 0L;
    private List<Image> mockImages = new ArrayList<>();

    @Override
    public void saveAll(List<Image> images) {
        mockImages = images.stream().map(
                image -> Image.builder()
                        .id(++autoGeneratedId)
                        .itemId(image.getItemId())
                        .itemType(image.getItemType())
                        .imageName(image.getImageName())
                        .isThumbnail(image.isThumbnail())
                        .build()
        ).toList();
    }


    @Override
    public List<String> findImageNamesByItemIdAndItemType(Long itemId, ItemType itemType) {
        return mockImages.stream()
                .filter(image -> Objects.equals(image.getId(), itemId) && image.getItemType().equals(itemType))
                .map(Image::getImageName).toList();
    }

    @Override
    public String findThumbnailByItemIdAndItemType(Long itemId, ItemType itemType) {
        return mockImages.stream()
                .filter(image -> Objects.equals(image.getId(), itemId) && image.getItemType().equals(itemType) && image.isThumbnail())
                .map(Image::getImageName).findFirst().orElse(null);
    }
}