package com.yzgeneration.evc.mock.usedItem;

import com.yzgeneration.evc.common.exception.CustomException;
import com.yzgeneration.evc.common.exception.ErrorCode;
import com.yzgeneration.evc.useditem.model.UsedItem;
import com.yzgeneration.evc.useditem.service.port.UsedItemRepository;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

public class FakeUsedItemRepository implements UsedItemRepository {

    private static Long autoGeneratedId = 0L;
    private final List<UsedItem> mockUsedItems = new ArrayList<>();

    @Override
    public UsedItem save(UsedItem usedItem) {
        UsedItem mockUsedItem = UsedItem.builder()
                .id(++autoGeneratedId)
                .itemDetails(usedItem.getItemDetails())
                .usedItemStatus(usedItem.getUsedItemStatus())
                .itemStats(usedItem.getItemStats())
                .createdAt(usedItem.getCreatedAt())
                .build();
        mockUsedItems.add(mockUsedItem);
        return mockUsedItem;
    }

    @Override
    public List<UsedItem> findAll() {
        return mockUsedItems;
    }

    @Override
    public UsedItem findById(Long usedItemId) {
        return mockUsedItems.stream()
                .filter(mockUsedItem -> Objects.equals(mockUsedItem.getId(), usedItemId))
                .findFirst()
                .orElseThrow(() -> new CustomException(ErrorCode.USEDITEM_NOT_FOUND));
    }
}
