package com.yzgeneration.evc.mock.chat;

import com.yzgeneration.evc.domain.chat.infrastructure.ChatRoomRepository;
import com.yzgeneration.evc.domain.chat.model.ChatRoom;
import com.yzgeneration.evc.exception.CustomException;
import com.yzgeneration.evc.exception.ErrorCode;

import java.util.ArrayList;
import java.util.List;

public class FakeChatRoomRepository implements ChatRoomRepository {

    private static Long autoGeneratedId = 0L;
    private final List<ChatRoom> data = new ArrayList<>();
    @Override
    public ChatRoom save(ChatRoom chatRoom) {
        if (chatRoom.getId() == null || chatRoom.getId() == 0) {
            ChatRoom newChatRoom = ChatRoom.builder()
                    .id(++autoGeneratedId)
                    .usedItemId(chatRoom.getUsedItemId())
                    .ownerId(chatRoom.getOwnerId())
                    .participationId(chatRoom.getParticipationId())
                    .createdAt(chatRoom.getCreatedAt())
                    .build();
            data.add(newChatRoom);
            return newChatRoom;
        } else {
            data.removeIf(item -> item.getId().equals(chatRoom.getId()));
            data.add(chatRoom);
            return chatRoom;
        }
    }

    @Override
    public ChatRoom getById(Long id) {
        return data.stream().filter(item -> item.getId().equals(id)).findFirst().orElseThrow(()-> new CustomException(ErrorCode.CHAT_NOT_FOUND));
    }
}
