package com.yzgeneration.evc.mock.chat;

import com.yzgeneration.evc.domain.chat.infrastructure.ChatRoomRepository;
import com.yzgeneration.evc.domain.chat.model.ChatRoom;
import com.yzgeneration.evc.domain.image.enums.ItemType;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

public class FakeChatRoomRepository implements ChatRoomRepository {

    private Long autoGeneratedId = 0L;
    private final List<ChatRoom> data = new ArrayList<>();
    @Override
    public ChatRoom save(ChatRoom chatRoom) {
        if (chatRoom.getId() == null || chatRoom.getId() == 0) {
            ChatRoom newChatRoom = ChatRoom.builder()
                    .id(++autoGeneratedId)
                    .itemId(chatRoom.getItemId())
                    .ownerId(chatRoom.getOwnerId())
                    .participantId(chatRoom.getParticipantId())
                    .itemType(chatRoom.getItemType())
                    .createdAt(chatRoom.getCreatedAt())
                    .build();
            data.add(newChatRoom);
            return newChatRoom;
        } else {
            data.removeIf(item -> item.getId().equals(chatRoom.getId()));
            data.add(chatRoom);
            return chatRoom;
        }
    }

    @Override
    public Optional<ChatRoom> findByItemIdAndItemTypeAndParticipantId(Long itemId, ItemType itemType, Long participantId) {
        for (ChatRoom datum : data) {
            if (datum.getItemId().equals(itemId) && datum.getItemType().equals(itemType) && datum.getParticipantId().equals(participantId)) {
                return Optional.of(datum);
            }
        }
        return Optional.empty();
    }

    @Override
    public ChatRoom getById(Long id) {
        return null;
    }

}
