package com.yzgeneration.evc.mock.chat;

import com.yzgeneration.evc.domain.chat.infrastructure.ChatRoomRepository;
import com.yzgeneration.evc.domain.chat.model.ChatRoom;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

public class FakeChatRoomRepository implements ChatRoomRepository {

    private Long autoGeneratedId = 0L;
    private final List<ChatRoom> data = new ArrayList<>();
    @Override
    public ChatRoom save(ChatRoom chatRoom) {
        if (chatRoom.getId() == null || chatRoom.getId() == 0) {
            ChatRoom newChatRoom = ChatRoom.builder()
                    .id(++autoGeneratedId)
                    .usedItemId(chatRoom.getUsedItemId())
                    .ownerId(chatRoom.getOwnerId())
                    .participantId(chatRoom.getParticipantId())
                    .createdAt(chatRoom.getCreatedAt())
                    .build();
            data.add(newChatRoom);
            return newChatRoom;
        } else {
            data.removeIf(item -> item.getId().equals(chatRoom.getId()));
            data.add(chatRoom);
            return chatRoom;
        }
    }

    @Override
    public Optional<ChatRoom> findByUsedItemIdAndParticipantId(Long usedItemId, Long participantId) {
        return data.stream()
                .filter(chatRoom -> chatRoom.getUsedItemId().equals(usedItemId) &&
                        chatRoom.getParticipantId().equals(participantId))
                .findFirst();
    }
}
