package com.yzgeneration.evc.mock.chat;

import com.yzgeneration.evc.domain.chat.infrastructure.ChatMemberRepository;
import com.yzgeneration.evc.domain.chat.model.ChatMember;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

public class FakeChatMemberRepository implements ChatMemberRepository {

    private static Long autoGeneratedId = 0L;
    private final List<ChatMember> data = new ArrayList<>();

    @Override
    public ChatMember save(ChatMember chatMember) {
        if (chatMember.getId() == null || chatMember.getId() == 0) {
            ChatMember newChatMember = ChatMember.builder()
                    .id(++autoGeneratedId)
                    .chatRoomId(chatMember.getChatRoomId())
                    .memberId(chatMember.getMemberId())
                    .isDeleted(chatMember.getIsDeleted())
                    .build();
            data.add(newChatMember);
            return newChatMember;
        } else {
            data.removeIf(item -> Objects.equals(item.getId(), chatMember.getId()));
            data.add(chatMember);
            return chatMember;
        }
    }
}
