package com.yzgeneration.evc.mock.member;

import com.yzgeneration.evc.member.model.Member;
import com.yzgeneration.evc.member.service.port.MemberRepository;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

public class FakeMemberRepository implements MemberRepository {

    private static Long autoGeneratedId = 0L;
    private final List<Member> data = new ArrayList<>();
    @Override
    public Member save(Member member) {
        if (member.getId() == null || member.getId() == 0) {
            Member newMember = Member.builder()
                    .id(++autoGeneratedId)
                    .memberRole(member.getMemberRole())
                    .memberStatus(member.getMemberStatus())
                    .memberPrivateInformation(member.getMemberPrivateInformation())
                    .memberAuthenticationInformation(member.getMemberAuthenticationInformation())
                    .build();
            data.add(newMember);
            return newMember;
        } else {
            data.removeIf(item -> Objects.equals(item.getId(), member.getId()));
            data.add(member);
            return member;
        }
    }
}
