package com.yzgeneration.evc.mock.member;

import com.yzgeneration.evc.verification.infrastructure.EmailVerificationRepository;
import com.yzgeneration.evc.verification.model.EmailVerification;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

public class FakeEmailVerificationRepository implements EmailVerificationRepository {

    private static Long autoGeneratedId = 0L;
    private final List<EmailVerification> data = new ArrayList<>();

    @Override
    public EmailVerification save(EmailVerification emailVerification) {
        if (emailVerification.getId() == null || emailVerification.getId() == 0) {
            EmailVerification newEmailVerification = EmailVerification.builder()
                    .id(++autoGeneratedId)
                    .emailVerificationType(emailVerification.getEmailVerificationType())
                    .emailAddress(emailVerification.getEmailAddress())
                    .verificationCode(emailVerification.getVerificationCode())
                    .isVerified(emailVerification.isVerified())
                    .memberId(emailVerification.getMemberId())
                    .build();
            data.add(newEmailVerification);
            return newEmailVerification;
        } else {
            data.removeIf(item -> Objects.equals(item.getId(), emailVerification.getId()));
            data.add(emailVerification);
            return emailVerification;
        }

    }
}
