package com.yzgeneration.evc.mock.delivery;

import com.yzgeneration.evc.domain.delivery.infrastructure.AddressRepository;
import com.yzgeneration.evc.domain.delivery.model.Address;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

public class FakeAddressRepository implements AddressRepository {
    private Long autoGeneratedId = 0L;
    private final List<Address> data = new ArrayList<>();

    @Override
    public Address save(Address address) {
        if (address.getId() == null || address.getId() == 0) {
            Address newAddress = Address.builder()
                    .id(++autoGeneratedId)
                    .basicAddress(address.getBasicAddress())
                    .detailAddress(address.getDetailAddress())
                    .latitude(address.getLatitude())
                    .longitude(address.getLongitude())
                    .build();
            data.add(newAddress);
            return newAddress;
        } else {
           data.removeIf(item -> item.getId().equals(address.getId()));
           data.add(address);
           return address;
        }
    }

    @Override
    public Optional<Address> findByMemberId(Long memberId) {
        for (Address datum : data) {
            if (datum.getId().equals(memberId)) return Optional.of(datum);
        }
        return Optional.empty();
    }

    @Override
    public Address getByMemberId(Long memberId) {
        return null;
    }

    public int getSize() {
        return data.size();
    }


}
